import type { SearchHistory, SearchResult } from "./types"

export const mockHistories: SearchHistory[] = [
  {
    id: "hist-001",
    keyword: "건설 현장 AI 안전 관리",
    createdAt: "2025-02-14T14:30:00Z",
    source: "auto",
    resultCounts: {
      report: 48,
      paper: 127,
      patent: 32,
      article: 15,
    },
  },
  {
    id: "hist-002",
    keyword: "LiDAR BIM 시공 품질 검사",
    createdAt: "2025-02-13T09:15:00Z",
    source: "manual",
    resultCounts: {
      report: 23,
      paper: 89,
      patent: 18,
      article: 7,
    },
  },
  {
    id: "hist-003",
    keyword: "강화학습 건설장비 자율운전",
    createdAt: "2025-02-10T16:45:00Z",
    source: "auto",
    resultCounts: {
      report: 15,
      paper: 56,
      patent: 12,
      article: 4,
    },
  },
  {
    id: "hist-004",
    keyword: "스마트 건설 IoT 센서 통합 플랫폼",
    createdAt: "2025-02-09T11:20:00Z",
    source: "manual",
    resultCounts: {
      report: 34,
      paper: 78,
      patent: 25,
      article: 12,
    },
  },
  {
    id: "hist-005",
    keyword: "디지털 트윈 기반 시설물 유지관리",
    createdAt: "2025-02-08T15:40:00Z",
    source: "auto",
    resultCounts: {
      report: 41,
      paper: 95,
      patent: 28,
      article: 9,
    },
  },
  {
    id: "hist-006",
    keyword: "3D 프린팅 건축 자재 개발",
    createdAt: "2025-02-07T10:15:00Z",
    source: "manual",
    resultCounts: {
      report: 19,
      paper: 67,
      patent: 22,
      article: 8,
    },
  },
  {
    id: "hist-007",
    keyword: "건설 로봇 자동화 시스템",
    createdAt: "2025-02-06T13:25:00Z",
    source: "auto",
    resultCounts: {
      report: 27,
      paper: 83,
      patent: 31,
      article: 11,
    },
  },
  {
    id: "hist-008",
    keyword: "친환경 건축 자재 성능 평가",
    createdAt: "2025-02-05T09:50:00Z",
    source: "manual",
    resultCounts: {
      report: 38,
      paper: 102,
      patent: 19,
      article: 14,
    },
  },
  {
    id: "hist-009",
    keyword: "지진 내진 설계 시뮬레이션",
    createdAt: "2025-02-04T16:10:00Z",
    source: "auto",
    resultCounts: {
      report: 31,
      paper: 91,
      patent: 16,
      article: 6,
    },
  },
  {
    id: "hist-010",
    keyword: "모듈러 건축 공법 최적화",
    createdAt: "2025-02-03T14:35:00Z",
    source: "manual",
    resultCounts: {
      report: 22,
      paper: 74,
      patent: 20,
      article: 10,
    },
  },
  {
    id: "hist-011",
    keyword: "건물 에너지 효율 개선 기술",
    createdAt: "2025-02-02T11:45:00Z",
    source: "auto",
    resultCounts: {
      report: 45,
      paper: 112,
      patent: 27,
      article: 13,
    },
  },
  {
    id: "hist-012",
    keyword: "스마트 그리드 건물 통합 시스템",
    createdAt: "2025-02-01T10:20:00Z",
    source: "manual",
    resultCounts: {
      report: 29,
      paper: 86,
      patent: 24,
      article: 7,
    },
  },
  {
    id: "hist-013",
    keyword: "VR AR 건설 현장 교육 콘텐츠",
    createdAt: "2025-01-31T15:55:00Z",
    source: "auto",
    resultCounts: {
      report: 18,
      paper: 62,
      patent: 15,
      article: 9,
    },
  },
  {
    id: "hist-014",
    keyword: "건설 폐기물 재활용 처리 기술",
    createdAt: "2025-01-30T09:30:00Z",
    source: "manual",
    resultCounts: {
      report: 35,
      paper: 98,
      patent: 21,
      article: 11,
    },
  },
  {
    id: "hist-015",
    keyword: "건축물 화재 안전 예측 시스템",
    createdAt: "2025-01-29T13:40:00Z",
    source: "auto",
    resultCounts: {
      report: 26,
      paper: 79,
      patent: 18,
      article: 8,
    },
  },
  {
    id: "hist-016",
    keyword: "터널 굴착 자동화 장비 개발",
    createdAt: "2025-01-28T11:15:00Z",
    source: "manual",
    resultCounts: {
      report: 21,
      paper: 71,
      patent: 26,
      article: 5,
    },
  },
  {
    id: "hist-017",
    keyword: "건설 현장 드론 측량 정밀도 향상",
    createdAt: "2025-01-27T14:50:00Z",
    source: "auto",
    resultCounts: {
      report: 33,
      paper: 88,
      patent: 23,
      article: 12,
    },
  },
  {
    id: "hist-018",
    keyword: "공동주택 소음 저감 기술",
    createdAt: "2025-01-26T10:25:00Z",
    source: "manual",
    resultCounts: {
      report: 28,
      paper: 76,
      patent: 17,
      article: 9,
    },
  },
  {
    id: "hist-019",
    keyword: "지하 구조물 안전 모니터링 센서",
    createdAt: "2025-01-25T16:05:00Z",
    source: "auto",
    resultCounts: {
      report: 37,
      paper: 94,
      patent: 29,
      article: 10,
    },
  },
  {
    id: "hist-020",
    keyword: "건설 현장 미세먼지 저감 방안",
    createdAt: "2025-01-24T09:40:00Z",
    source: "manual",
    resultCounts: {
      report: 24,
      paper: 81,
      patent: 14,
      article: 7,
    },
  },
  {
    id: "hist-021",
    keyword: "콘크리트 품질 실시간 모니터링",
    createdAt: "2025-01-23T13:20:00Z",
    source: "auto",
    resultCounts: {
      report: 30,
      paper: 85,
      patent: 22,
      article: 8,
    },
  },
  {
    id: "hist-022",
    keyword: "건축물 BIM 기반 유지관리 시스템",
    createdAt: "2025-01-22T11:50:00Z",
    source: "manual",
    resultCounts: {
      report: 42,
      paper: 106,
      patent: 25,
      article: 13,
    },
  },
  {
    id: "hist-023",
    keyword: "건설 현장 작업자 위치 추적 기술",
    createdAt: "2025-01-21T15:30:00Z",
    source: "auto",
    resultCounts: {
      report: 20,
      paper: 68,
      patent: 19,
      article: 6,
    },
  },
]

export const mockResults: Record<string, SearchResult[]> = {
  "hist-001": [
    {
      id: "rpt-001",
      type: "report",
      title: "AI 기반 건설 현장 안전관리 시스템 개발 및 실증",
      authors: ["김철수", "이영희", "박민준"],
      organization: "한국건설기술연구원",
      publishedAt: "2024-12-20",
      abstract:
        "본 연구는 컴퓨터 비전과 딥러닝 기술을 활용하여 건설 현장의 작업자 안전을 실시간으로 모니터링하는 시스템을 개발하였다. YOLOv8 기반 객체 탐지 모델을 통해 안전모, 안전화, 안전조끼 등 개인 보호 장비(PPE) 착용 여부를 자동으로 감지하고, 미착용 시 즉시 경보를 발송한다. 실제 건설 현장 3곳에서 6개월간 실증 실험을 수행한 결과, PPE 착용률이 평균 18.5% 향상되었으며, 안전사고 발생률은 27.3% 감소하였다.",
      keywords: ["AI", "건설안전", "컴퓨터비전", "실시간모니터링", "PPE"],
      url: "https://ntis.go.kr/project/pjtInfo.do?pjtId=1234567890",
      similarity: 93,
    },
    {
      id: "rpt-002",
      type: "report",
      title: "스마트 건설을 위한 IoT 센서 네트워크 구축 및 안전관리 플랫폼 개발",
      authors: ["박민수", "정수진"],
      organization: "서울대학교 건설환경종합연구소",
      publishedAt: "2024-09-10",
      abstract:
        "건설 현장의 안전과 효율성을 향상시키기 위해 IoT 센서 네트워크를 구축하고 실시간 데이터 수집·분석 플랫폼을 개발하였다. 환경 센서(온도, 습도, 미세먼지), 진동 센서, 위치 추적 센서 등을 통합하여 작업자의 안전 상황을 모니터링하며, 위험 상황 발생 시 자동으로 관리자에게 알림을 전송한다. LoRaWAN 기반 저전력 통신으로 넓은 현장에서도 안정적인 데이터 수집이 가능하다.",
      keywords: ["IoT", "스마트건설", "센서네트워크", "안전관리", "LoRaWAN"],
      url: "https://ntis.go.kr/project/pjtInfo.do?pjtId=1234567891",
      similarity: 78,
    },
    {
      id: "rpt-003",
      type: "report",
      title: "딥러닝 기반 건설 현장 위험 상황 예측 시스템",
      authors: ["최지훈", "강민아", "오세영"],
      organization: "고려대학교 건축사회환경공학부",
      publishedAt: "2024-08-05",
      abstract:
        "건설 현장에서 발생할 수 있는 위험 상황을 사전에 예측하기 위해 LSTM 기반 시계열 분석 모델을 개발하였다. 과거 10년간의 건설 안전사고 데이터(15,234건)를 학습하여 날씨, 작업 유형, 인원 배치, 장비 가동률 등의 변수를 기반으로 위험도를 예측한다. 실증 테스트 결과, 사고 예측 정확도 82.7%를 달성하였으며, 위험도가 높은 시간대에 작업을 조정하여 안전성을 크게 향상시킬 수 있었다.",
      keywords: ["딥러닝", "위험예측", "LSTM", "건설안전", "시계열분석"],
      url: "https://ntis.go.kr/project/pjtInfo.do?pjtId=1234567892",
      similarity: 85,
    },
    {
      id: "rpt-004",
      type: "report",
      title: "웨어러블 센서 기반 작업자 생체신호 모니터링 시스템",
      authors: ["임하늘"],
      organization: "연세대학교 의공학과",
      publishedAt: "2024-07-15",
      abstract:
        "건설 현장 작업자의 심박수, 체온, 혈중 산소 포화도 등 생체신호를 실시간으로 측정하고 분석하는 웨어러블 센서 시스템을 개발하였다. 고온 환경에서의 온열질환 위험을 조기에 감지하고, 과로로 인한 사고를 예방할 수 있다. 현장 관리자는 대시보드를 통해 전체 작업자의 건강 상태를 한눈에 파악하고, 이상 징후 발생 시 즉시 대응할 수 있다.",
      keywords: ["웨어러블센서", "생체신호", "건강모니터링", "온열질환", "작업자안전"],
      url: "https://ntis.go.kr/project/pjtInfo.do?pjtId=1234567893",
      similarity: 72,
    },
    {
      id: "rpt-005",
      type: "report",
      title: "AR 기술을 활용한 건설 현장 안전교육 콘텐츠 개발",
      authors: ["윤서연", "한도윤"],
      organization: "성균관대학교 건설환경공학과",
      publishedAt: "2024-06-20",
      abstract:
        "증강현실(AR) 기술을 활용하여 건설 현장 작업자를 위한 몰입형 안전교육 콘텐츠를 개발하였다. 실제 현장 환경을 3D로 재현하고, 위험 상황 시뮬레이션을 통해 작업자가 안전 절차를 체득할 수 있도록 하였다. 전통적인 이론 교육 대비 학습 효과가 45% 향상되었으며, 교육 이수율도 크게 개선되었다.",
      keywords: ["AR", "증강현실", "안전교육", "시뮬레이션", "몰입형학습"],
      url: "https://ntis.go.kr/project/pjtInfo.do?pjtId=1234567894",
      similarity: 68,
    },
    {
      id: "paper-001",
      type: "paper",
      title:
        "Deep Learning-Based PPE Detection for Construction Safety Management",
      authors: ["Kim, J.", "Lee, S.", "Park, M."],
      organization: "KAIST",
      publishedAt: "2024-11-15",
      abstract:
        "This paper presents a novel deep learning approach for detecting personal protective equipment (PPE) in construction sites. We propose an enhanced YOLO architecture that achieves 96.2% mAP on a dataset of 50,000 construction site images...",
      keywords: [
        "Deep Learning",
        "PPE Detection",
        "Construction Safety",
        "YOLO",
        "Computer Vision",
      ],
      url: "https://doi.org/10.1016/j.autcon.2024.105234",
      similarity: 91,
    },
    {
      id: "paper-002",
      type: "paper",
      title: "IoT-Enabled Real-Time Safety Monitoring in Smart Construction",
      authors: ["Chen, X.", "Wang, Y.", "Zhang, L."],
      organization: "Tsinghua University",
      publishedAt: "2024-10-08",
      abstract:
        "We develop an IoT-based framework for real-time safety monitoring in construction sites, integrating environmental sensors, wearables, and edge computing...",
      keywords: [
        "IoT",
        "Smart Construction",
        "Safety Monitoring",
        "Edge Computing",
        "Sensor Networks",
      ],
      url: "https://doi.org/10.1016/j.jclepro.2024.142856",
      similarity: 87,
    },
    {
      id: "patent-001",
      type: "patent",
      title: "건설 현장 작업자 안전 관리를 위한 AI 기반 실시간 모니터링 시스템",
      authors: ["김현수"],
      organization: "삼성물산 건설부문",
      publishedAt: "2024-09-20",
      abstract:
        "본 발명은 건설 현장에 설치된 다수의 카메라로부터 영상을 수집하고, AI 모델을 통해 작업자의 안전모, 안전화 등 보호장구 착용 여부를 실시간으로 판별하여 관리자에게 알림을 제공하는 시스템에 관한 것이다. 또한, 작업자의 행동 패턴을 분석하여 위험 상황을 사전에 예측할 수 있다.",
      keywords: ["AI", "안전관리", "실시간모니터링", "건설현장", "보호장구"],
      url: "https://doi.org/10.8080/KR-10-2024-0123456",
      similarity: 89,
    },
    {
      id: "article-001",
      type: "article",
      title: "AI가 건설 현장 안전을 책임진다... 스마트 안전관리 시스템 확산",
      authors: ["이기자"],
      organization: "건설경제신문",
      publishedAt: "2025-01-10",
      abstract:
        "국내 주요 건설사들이 AI 기반 안전관리 시스템 도입을 확대하고 있다. 현대건설은 지난해부터 주요 현장에 AI 카메라를 설치해 작업자의 안전모 착용 여부를 실시간으로 감지하고 있으며, GS건설은 IoT 센서와 웨어러블 기기를 결합한 통합 안전관리 플랫폼을 개발 중이다. 전문가들은 AI 기술이 건설 안전사고를 획기적으로 줄일 수 있을 것으로 기대하고 있다.",
      keywords: ["AI", "건설안전", "스마트시스템", "건설업계", "안전사고예방"],
      similarity: 76,
    },
  ],
  "hist-002": [
    {
      id: "rpt-101",
      type: "report",
      title: "드론 LiDAR 기반 건축물 시공 품질 자동 검사 시스템 개발",
      authors: ["이재호", "김민지"],
      organization: "한국건설기술연구원",
      publishedAt: "2024-11-30",
      abstract:
        "드론 탑재 LiDAR를 활용하여 건축물 시공 품질을 자동으로 검사하는 시스템을 개발하였다. BIM 모델과 LiDAR 스캔 데이터를 정합하여 시공 오차를 ±5mm 정밀도로 탐지할 수 있으며, 기존 육안 검사 대비 검사 시간을 70% 단축하였다. 포인트 클라우드 처리 알고리즘을 최적화하여 대형 건축물(연면적 10만㎡ 이상)도 24시간 이내에 전수 검사가 가능하다.",
      keywords: ["LiDAR", "BIM", "시공품질", "드론", "자동검사"],
      url: "https://ntis.go.kr/project/pjtInfo.do?pjtId=2234567890",
      similarity: 95,
    },
    {
      id: "rpt-102",
      type: "report",
      title: "BIM 기반 건축 시공 품질관리 플랫폼 구축",
      authors: ["정우성", "홍길동"],
      organization: "경희대학교 건축공학과",
      publishedAt: "2024-10-12",
      abstract:
        "BIM 모델을 중심으로 설계, 시공, 품질검사를 통합 관리하는 플랫폼을 개발하였다. 모바일 앱을 통해 현장에서 품질 이슈를 실시간으로 기록하고, BIM 모델상의 정확한 위치에 자동으로 매핑된다. 품질 데이터는 블록체인에 저장되어 위변조가 불가능하며, 준공 후 유지보수 단계에서도 활용 가능하다.",
      keywords: ["BIM", "품질관리", "블록체인", "통합플랫폼", "디지털트윈"],
      url: "https://ntis.go.kr/project/pjtInfo.do?pjtId=2234567891",
      similarity: 82,
    },
    {
      id: "paper-101",
      type: "paper",
      title: "Automated Quality Inspection of Building Construction Using LiDAR",
      authors: ["Zhang, H.", "Liu, Y.", "Wang, K."],
      organization: "MIT",
      publishedAt: "2024-09-25",
      abstract:
        "We present an automated quality inspection framework that leverages LiDAR point clouds and BIM models for construction quality control...",
      keywords: [
        "LiDAR",
        "Quality Inspection",
        "Point Cloud",
        "BIM",
        "Automation",
      ],
      url: "https://doi.org/10.1016/j.autcon.2024.105678",
      similarity: 92,
    },
  ],
  "hist-003": [
    {
      id: "rpt-201",
      type: "report",
      title: "강화학습 기반 건설장비 자율주행 및 협업 시뮬레이션 플랫폼",
      authors: ["박지성", "이수민", "김태현"],
      organization: "KAIST 건설및환경공학과",
      publishedAt: "2024-10-18",
      abstract:
        "PPO와 SAC 강화학습 알고리즘을 활용하여 굴삭기, 덤프트럭, 지게차 등 건설장비의 자율주행 정책을 학습하는 시뮬레이션 플랫폼을 개발하였다. Unity 엔진 기반 3D 가상 현장에서 다중 에이전트 협업 시나리오를 구현하였으며, 충돌 회피 및 작업 효율 최적화를 동시에 달성하였다. HIL(Hardware-in-the-Loop) 테스트를 통해 실제 장비 제어기와의 연동 가능성을 검증하였다.",
      keywords: ["강화학습", "자율주행", "건설장비", "시뮬레이션", "다중에이전트"],
      url: "https://ntis.go.kr/project/pjtInfo.do?pjtId=3234567890",
      similarity: 96,
    },
    {
      id: "paper-201",
      type: "paper",
      title:
        "Reinforcement Learning for Autonomous Construction Equipment Navigation",
      authors: ["Park, S.", "Kim, D.", "Lee, J."],
      organization: "Seoul National University",
      publishedAt: "2024-08-30",
      abstract:
        "This paper presents a reinforcement learning approach for autonomous navigation of construction equipment in dynamic environments...",
      keywords: [
        "Reinforcement Learning",
        "Autonomous Navigation",
        "Construction Equipment",
        "PPO",
        "Simulation",
      ],
      url: "https://doi.org/10.1016/j.robot.2024.104123",
      similarity: 94,
    },
  ],
}
